### ISSUE TITLE
MoM of classification `group_classifications` value It is replaced every time the layer is changed.

### ISSUE THREAD

**Issue by nbitboy** [enoch3712/ExtractThinker#107]
I am using MoM classification and noticed that it only returns one result from the final layer. This makes me wonder whether the other layers are used. It appears that no matter the values from the previous layers, they are not carried forward as they are always being replaced (`group_classifications`). If I got something wrong, please let me know.

![image](https://github.com/user-attachments/assets/a277574a-6b1d-4dad-8fce-df8ff8641504)

**Comment by nbitboy** [comment]
Wow thank you for your fixed. I can see the edited code from the branch name "107-mom-of-classification-group_classifications-value-it-is-replaced-every-time-the-layer-is-changed" right?

If it yes.
I don't see a commit about this issue but I see #108. It means this issue is in the fix process right?

**Comment by nbitboy** [comment]
I see you fixed the indentation, thanks @enoch3712 .

**Comment by enoch3712** [comment]
@nbitboy 

Hey! Yes the github closes eveything automatically, a bit annoying. 

Yes its done! And keep them coming and i will fix them quite fast. 

Please look at [test_mom_classification_layers](https://github.com/enoch3712/ExtractThinker/blob/v0.0.27/tests/test_classify.py) test, it has exactly the use case you said, even in debug goes into the layers

**Comment by nbitboy** [comment]
Sorry I don't know git automatically have delay. I thank you so much for your fixed. @enoch3712
