### ISSUE TITLE
Classification with Strategy, Mapping of Contract and image comparison 

### ISSUE THREAD

**Issue by enoch3712** [enoch3712/ExtractThinker#11]

**Comment by ChristianWeyer** [comment]
Are you still working on this project @enoch3712 ?

**Comment by enoch3712** [comment]
Hello!

Yes. Sorry for the delay and ghosting. Was integrated in a Startup, i will
boost work this week.

Take care,

Christian Weyer ***@***.***> escreveu (segunda, 12/08/2024
à(s) 12:36):
