### ISSUE TITLE
Classify with image don't use content in `input_data` variable

### ISSUE THREAD

**Issue by nbitboy** [enoch3712/ExtractThinker#115]
I tried to look for the usage of content when set is_classify_image is True, but I don't see it in `def _classify` of extractor.py file. 

![image](https://github.com/user-attachments/assets/9ba1388d-07d5-444e-9611-9f400da9bdba)

**Comment by enoch3712** [comment]
Hello @nbitboy !

I just tested, and it works as expected. Just follow/debug [test_with_image() ](https://github.com/enoch3712/ExtractThinker/blob/main/tests/test_classify.py) and you see how it works. 

The usage and flow is a bit below. 

<img width="743" alt="image" src="https://github.com/user-attachments/assets/3b87d6e9-2491-4782-b229-0972240f81b7" />

You need to put the images inside and they are injected into the prompt. 

Debug:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/eb1b4fa8-1f17-41da-befe-a79a4d5d6ca3" />

You need to inject the image into the classification:
<img width="789" alt="image" src="https://github.com/user-attachments/assets/1f202537-1e0f-4ab7-9b62-2dfe15a00e0d" />

**Comment by enoch3712** [comment]
@nbitboy 

You can close if is solved :) 

Or we keep discussing

**Comment by nbitboy** [comment]
I test this function with TEST_IMAGE_PATH = "test_image.jpeg".
![image](https://github.com/user-attachments/assets/4dc6de85-ff65-4f54-95ee-1c2707278c7b)

I think messages before sending to inference with mllm should have the path of the test file (TEST_IMAGE_PATH) but my messages don't have it.
![image](https://github.com/user-attachments/assets/56307bae-7206-4849-ab83-76c5bcee3b00)

**Comment by enoch3712** [comment]
@nbitboy 

https://github.com/enoch3712/ExtractThinker/pull/116

Tell me what you think. 

Thanks for the heads up! Just to give you a context, this project was made by accident, based on the medium posts. Most of the code are still not fully well structure. 

for the version 0.1.0 i will fix all of this, because most of this code doesnt make sense

**Comment by enoch3712** [comment]
@nbitboy 

https://github.com/enoch3712/ExtractThinker/issues/117

**Comment by nbitboy** [comment]
Thank you so much for fixing the my problem completely! I think it great. 

I like your project it is very useful. I encourage you to keep doing it.

**Comment by mophilly** [comment]
> I like your project it is very useful. I encourage you to keep doing it.

I agree!

**Comment by enoch3712** [comment]
@nbitboy 
@mophilly 

This project will keep going, and i will launch a proper version in a few days. Thank you for your support!
