### ISSUE TITLE
docx2txt module not found

### ISSUE THREAD

**Issue by mophilly** [enoch3712/ExtractThinker#135]
Using PyCharm 2024.3.1.1 (pro), python 3.12, extract-thinker 0.28. MacOS Sequoia 15.2 (24C101)
This error was raised after updating extract-thinker via the pyCharm packages tool.
docx2txt 0.8 is in site-packages in the .venv path. 

I tried... 
    uninstalling docx2txt and reinstalling it, no joy. 
    uninstalled extract-thinker and reinstalled. error still raised.

```Traceback (most recent call last):
  File ".../pyCharmProjects/Extract-thinker/et_flow_orchestrator.py", line 41, in <module>
    from et_run_statement_processor import process_run_statement
  File ".../pyCharmProjects/Extract-thinker/et_statement_processor.py", line 4, in <module>
    from extract_thinker import Extractor, DocumentLoaderPyPdf
  File ".../pyCharmProjects/Extract-thinker/.venv/lib/python3.12/site-packages/extract_thinker/__init__.py", line 22, in <module>
    from .document_loader.document_loader_doc2txt import DocumentLoaderDoc2txt
  File ".../pyCharmProjects/Extract-thinker/.venv/lib/python3.12/site-packages/extract_thinker/document_loader/document_loader_doc2txt.py", line 3, in <module>
    import docx2txt
ModuleNotFoundError: No module named 'docx2txt'

Process finished with exit code 1```

**Comment by enoch3712** [comment]
Hey @mophilly 

`pip install docx2txt
`

Im taking care of this as we speak. Changing the documentation, because in python you need to this (that looks horrible)

<img width="649" alt="image" src="https://github.com/user-attachments/assets/9d9755e8-348f-45cb-92dc-7ac7c15d9c35" />

So the dependencias dont blow up when you use 1% of the features.

**Comment by mophilly** [comment]
FYI... extract-thinker 0.27 doesn't raise that error. 
Thanks for being so responsive. It really helps!

**Comment by enoch3712** [comment]
@mophilly 

`FYI... extract-thinker 0.27 doesn't raise that error.`

interesting...

No worries, thank you for the help. I will be here in the next hours. I will be very responsive if you need me

**Comment by mophilly** [comment]
BTW, ```pip install docx2txt``` did not resolve the issue for me using 0.28. 

It may be my local set up. I uninstalled docx2txt, purged the pip cache, and re-installed, but no joy. Also, checked paths and such, and all looks correct. I sense that I am overlooking something.

**Comment by enoch3712** [comment]
@mophilly 

Going to solve it 0.0.29. 

2 mins

**Comment by enoch3712** [comment]
@mophilly 

Actually, is on the depency list. You should be able to install it.

Can you create a new venv?

make sure the docx2txt is there?

**Comment by mophilly** [comment]
I can recreate the .venv... I think. New idea to me. I will research. At worst I can save off the project files and create an pycharm project. 

docx2txt is definitely there. pip show docx2txt returns info.

**Comment by mophilly** [comment]
I built a new project in PyCharm and installed extract-thinker 0.0.28. Same problem with docx2txt. 0.0.27 runs ok. 
It was time for me to start from a clean setup so all good.

**Comment by enoch3712** [comment]
@mophilly 

Checking now. I get back to you soon

**Comment by enoch3712** [comment]
@

**Comment by enoch3712** [comment]
@mophilly 

Thank you for the wait. 

Can i fix it, its working, but only in python 3.12. What version are you using? 

Python 3.13 has a completely different problem. Gonna fix that one too. 

0.0.29

**Comment by mophilly** [comment]
I am using python 3.12. If python 3.13 has advantages, then I can upgrade.

**Comment by enoch3712** [comment]
@mophilly Not really for this. 

Keep it this way, its working with 3.12

**Comment by mophilly** [comment]
Just tried my project with 0.0.29. It raised the error about "import docx2txt".

**Comment by enoch3712** [comment]
@mophilly 

```
import os
from typing import List
from dotenv import load_dotenv
from extract_thinker import Extractor
from extract_thinker import Contract
from extract_thinker import DocumentLoaderDoc2txt
from pydantic import BaseModel, field_validator
load_dotenv()

class InvoiceLine(BaseModel):
    description: str
    quantity: int
    unit_price: float
    amount: float

    @field_validator('quantity', mode='before')
    def convert_quantity_to_int(cls, v):
        if isinstance(v, float):
            return int(v)
        return v

class InvoiceContract(Contract):
    invoice_number: str
    invoice_date: str
    lines: List[InvoiceLine]
    total_amount: float

# Arrange
cwd = os.getcwd()
test_file_path = os.path.join(cwd, "invoice.docx")

extractor = Extractor()
extractor.load_document_loader(
	DocumentLoaderDoc2txt()
)
extractor.load_llm("gpt-4o-mini")

# Act
result = extractor.extract(test_file_path, InvoiceContract)

print(result)
```

install venv:
`python3.12 -m venv venv
`
change to venv:
```
# Windows
.\venv\Scripts\activate

# Unix/Linux/Mac
source venv/bin/activate
```

run file:
`python testExtract.py`

Just did it like this. Is this what you are doing?

**Comment by mophilly** [comment]
@enoch3712 

Here is the processing part, without the some logging code removed to make it easier to read.

```import logging
from dotenv import load_dotenv
from pydantic import ValidationError
from extract_thinker import Extractor, DocumentLoaderPyPdf
from models.receipt import RunStatementContract

load_dotenv()

def process_run_statement(input_path: str, output_path: str, log_processor=None):

    # create a document loader
    document_loader = DocumentLoaderPyPdf()

    # create the extractor
    extractor = Extractor()
    extractor.load_document_loader(document_loader)
    extractor.load_llm("gpt-4o-mini")  # or any other supported model

    # Extract data from your document
    result = extractor.extract(input_path, StatementContract, vision=True)

    validated_data = RunStatementContract.model_validate(result)
    # Write JSON object to the file system
    with open(output_path, "w") as file:
         json_data = validated_data.model_dump_json()
         file.write(json_data)
```

**Comment by enoch3712** [comment]
@mophilly 

```
import os
from typing import List
from dotenv import load_dotenv
from extract_thinker import Extractor
from extract_thinker import Contract
from extract_thinker import DocumentLoaderDoc2txt
from extract_thinker import DocumentLoaderPyPdf
from pydantic import BaseModel, field_validator, ValidationError

load_dotenv()

class InvoiceLine(BaseModel):
    description: str
    quantity: int
    unit_price: float
    amount: float

    @field_validator('quantity', mode='before')
    def convert_quantity_to_int(cls, v):
        if isinstance(v, float):
            return int(v)
        return v

class InvoiceContract(Contract):
    invoice_number: str
    invoice_date: str
    lines: List[InvoiceLine]
    total_amount: float

cwd = os.getcwd()
test_file_path = os.path.join(cwd, "invoice.pdf")

document_loader = DocumentLoaderPyPdf()

extractor = Extractor()
extractor.load_document_loader(document_loader)
extractor.load_llm("gpt-4o-mini")

result = extractor.extract(test_file_path, InvoiceContract, vision=True)

print(result)
```

This worked. I dont see anything related with doc2txt here

**Comment by mophilly** [comment]
That good to hear. The only differences between your example and mine is the import statements. I will play with that. I will look again at the PyCharm and more deeply in the venv. Maybe it is a file permission thing.

**Comment by mophilly** [comment]
This is resolved. The problem was in PyCharm. I am a new user of that tool. The default out-of-box settings worked fine for the first project or two. After the last update of PyCharm, and me adding more projects, the python path was empty. It was resolved by adding a defined run template for the project.
