### ISSUE TITLE
Tesseract only extract from png images and not jpeg?

### ISSUE THREAD

**Issue by spundhan** [enoch3712/ExtractThinker#151]
Normally tesseract should extract from jpeg images as well. Any reason why it throws an exception for jpg image?

**Comment by enoch3712** [comment]
Hello @spundhan!

Just tested, you are right!. Its a bug, forgot to put on the the SUPPORTED_FORMATS

`    SUPPORTED_FORMATS = ["jpeg", "png", "bmp", "tiff", "pdf"]
`

Give me 5 mins, gonna do an hotfix

**Comment by enoch3712** [comment]
@spundhan You can update to 0.0.31, will work just fine.

Thanks for the heads up!

**Comment by spundhan** [comment]
Thanks! You are awesome! Merry Christmas!
