### ISSUE TITLE
How to implement Groq llm

### ISSUE THREAD

**Issue by harinisri2001** [enoch3712/ExtractThinker#153]
In extractor.load_llm()  How to use Groq llm models with api key?

**Comment by enoch3712** [comment]
Hello @harinisri2001 !

```
    extractor = Extractor(document_loader)
    extractor.load_llm("groq/llama-3.1-70b-versatile")
```

Dont forgot GROQ_API_KEY in env

This should do it :) 

Gonna add to the documentation
